apiVersion: v1
kind: Service
metadata:
# base와 동일하게 명시해서 patch시 어떤 service에 대한 수정인지 kustomize가 인식
  name: app
spec:
  ports:
  # spec.ports 에서는 port가 key다.
  # kustomize는 k8s spec에 대한 awareness가 있으므로
  # key 속성을 파악하는것이 중요하다.
  - port: 8080
    targetPort: 8080