spring:
  application:
    name: redis-session-pattern
  redis:
    port: 6379
    host: redis-host
    password: redis-password
    lettuce:
      pool:
        max-active: 10
        max-idle: 10
        min-idle: 2
        max-wait: 30
    database: 0

  session:
    store-type: redis
    redis:
      flush-mode: on_save
      save-mode: always
      namespace: mysession
    timeout: 60

server:
  port: 8080
