apiVersion: apps/v1
kind: Deployment
metadata:
  name: springboot-configmap-pattern
  labels:
    app: springboot-configmap-pattern
spec:
  replicas: 1
  selector:
    matchLabels:
      app: springboot-configmap-pattern
  template:
    metadata:
      labels:
        app: springboot-configmap-pattern
    spec:
      containers:
      - name: springboot-configmap-pattern
        image: zzonsang2/springboot-configmap-pattern:0.0.1
        ports:
        - containerPort: 8080
        imagePullPolicy: Always
        resources:
          requests:
            memory: 128Mi            
          limits:
            memory: 512Mi 
        livenessProbe:
          httpGet:
            path: /actuator/health
            port: 8080
          initialDelaySeconds: 60
          periodSeconds: 20
        readinessProbe:
          httpGet:
            path: /actuator/health
            port: 8080
          initialDelaySeconds: 60
          periodSeconds: 20
