apiVersion: v1
kind: Service
metadata:
  name: springboot-configmap-pattern
spec:
  ports:
  - name: "http"
    port: 8080
    targetPort: 8080
  selector:
    app: springboot-configmap-pattern
  type: NodePort
