apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"extensions/v1beta1","kind":"Deployment","metadata":{"annotations":{},"name":"alertmanager-user","namespace":"zcp-system"},"spec":{"replicas":1,"selector":{"matchLabels":{"component":"alertmanager"}},"template":{"metadata":{"labels":{"component":"alertmanager"},"name":"alertmanager-user"},"spec":{"affinity":{"nodeAffinity":{"requiredDuringSchedulingIgnoredDuringExecution":{"nodeSelectorTerms":[{"matchExpressions":[{"key":"beta.kubernetes.io/arch","operator":"In","values":["amd64"]},{"key":"node-role.kubernetes.io/management","operator":"Exists"}]}]}}},"containers":[{"args":["--config.file=/etc/alertmanager/config.yml","--storage.path=/alertmanager"],"image":"registry.au-syd.bluemix.net/cloudzcp/alertmanager:v0.14.0","livenessProbe":{"failureThreshold":3,"httpGet":{"path":"/api/v1/status","port":9093,"scheme":"HTTP"},"initialDelaySeconds":30,"periodSeconds":10,"successThreshold":1,"timeoutSeconds":30},"name":"alertmanager","ports":[{"containerPort":9093,"name":"alertmanager","protocol":"TCP"}],"readinessProbe":{"failureThreshold":3,"httpGet":{"path":"/api/v1/status","port":9093,"scheme":"HTTP"},"initialDelaySeconds":30,"periodSeconds":10,"successThreshold":1,"timeoutSeconds":30},"resources":{"limits":{"cpu":"100m","memory":"100Mi"},"requests":{"cpu":"100m","memory":"100Mi"}},"volumeMounts":[{"mountPath":"/etc/alertmanager","name":"config-volume"},{"mountPath":"/alertmanager","name":"alertmanager"},{"mountPath":"/etc/alertmanager-templates","name":"alertmanager-templates-volume"},{"mountPath":"/etc/localtime","name":"tz-config"}]}],"restartPolicy":"Always","tolerations":[{"effect":"NoSchedule","key":"management","operator":"Equal","value":"true"}],"volumes":[{"configMap":{"name":"alertmanager-user"},"name":"config-volume"},{"configMap":{"name":"alertmanager-templates"},"name":"alertmanager-templates-volume"},{"emptyDir":{},"name":"alertmanager"},{"hostPath":{"path":"/usr/share/zoneinfo/Asia/Seoul"},"name":"tz-config"}]}}}}
  creationTimestamp: 2019-05-23T00:53:20Z
  generation: 2
  labels:
    component: alertmanager-user
  name: alertmanager-user
  namespace: zcp-system
  resourceVersion: "122915541"
  selfLink: /apis/extensions/v1beta1/namespaces/zcp-system/deployments/alertmanager-user
  uid: 28bae5cd-7cf5-11e9-882a-9a8724ad4230
spec:
  progressDeadlineSeconds: 2147483647
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      component: alertmanager-user
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        component: alertmanager-user
      name: alertmanager-user
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: beta.kubernetes.io/arch
                operator: In
                values:
                - amd64
              - key: node-role.kubernetes.io/management
                operator: Exists
      containers:
      - args:
        - --config.file=/etc/alertmanager/config.yml
        - --storage.path=/alertmanager
        image: registry.au-syd.bluemix.net/cloudzcp/alertmanager:v0.14.0
        imagePullPolicy: IfNotPresent
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /api/v1/status
            port: 9093
            scheme: HTTP
          initialDelaySeconds: 30
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 30
        name: alertmanager
        ports:
        - containerPort: 9093
          name: alertmanager
          protocol: TCP
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /api/v1/status
            port: 9093
            scheme: HTTP
          initialDelaySeconds: 30
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 30
        resources:
          limits:
            cpu: 100m
            memory: 100Mi
          requests:
            cpu: 100m
            memory: 100Mi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /etc/alertmanager
          name: config-volume
        - mountPath: /alertmanager
          name: alertmanager
        - mountPath: /etc/alertmanager-templates
          name: alertmanager-templates-volume
        - mountPath: /etc/localtime
          name: tz-config
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      tolerations:
      - effect: NoSchedule
        key: management
        operator: Equal
        value: "true"
      volumes:
      - configMap:
          defaultMode: 420
          name: alertmanager-user
        name: config-volume
      - configMap:
          defaultMode: 420
          name: alertmanager-templates
        name: alertmanager-templates-volume
      - emptyDir: {}
        name: alertmanager
      - hostPath:
          path: /usr/share/zoneinfo/Asia/Seoul
          type: ""
        name: tz-config
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: 2019-05-23T00:53:20Z
    lastUpdateTime: 2019-05-23T00:53:20Z
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  observedGeneration: 2
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1
