apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
  creationTimestamp: 2020-03-30T01:45:53Z
  generation: 1
  labels:
    app: elasticsearch
    component: elasticsearch
    role: client
  name: elasticsearch-client
  namespace: zcp-system
  resourceVersion: "120199091"
  selfLink: /apis/extensions/v1beta1/namespaces/zcp-system/deployments/elasticsearch-client
  uid: 18270093-8148-4dee-8540-7604b50a430f
spec:
  progressDeadlineSeconds: 2147483647
  replicas: 1
  revisionHistoryLimit: 2147483647
  selector:
    matchLabels:
      app: elasticsearch
      component: elasticsearch
      role: client
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: elasticsearch
        component: elasticsearch
        role: client
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: beta.kubernetes.io/arch
                operator: In
                values:
                - amd64
              - key: role
                operator: In
                values:
                - management
      containers:
      - env:
        - name: ES_JAVA_OPTS
          value: -Xms1024m -Xmx1024m
        image: registry.au-syd.bluemix.net/cloudzcp/elasticsearch:6.3.1
        imagePullPolicy: IfNotPresent
        name: es-client
        ports:
        - containerPort: 9200
          name: rest
          protocol: TCP
        - containerPort: 9300
          name: internal
          protocol: TCP
        resources:
          limits:
            memory: 2048M
        securityContext:
          capabilities:
            add:
            - IPC_LOCK
          privileged: false
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /usr/share/elasticsearch/data
          name: elasticsearch-data
        - mountPath: /usr/share/elasticsearch/config/elasticsearch.yml
          name: elasticsearch-conf
          subPath: elasticsearch.yml
      dnsPolicy: ClusterFirst
      initContainers:
      - command:
        - chmod
        - "777"
        - /data-dir
        image: registry.au-syd.bluemix.net/cloudzcp/elasticsearch:6.3.1
        imagePullPolicy: IfNotPresent
        name: chmod
        resources: {}
        securityContext:
          privileged: true
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /data-dir
          name: elasticsearch-data
      - command:
        - sysctl
        - -w
        - vm.max_map_count=262144
        image: registry.au-syd.bluemix.net/cloudzcp/elasticsearch:6.3.1
        imagePullPolicy: IfNotPresent
        name: sysctl
        resources: {}
        securityContext:
          privileged: true
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      serviceAccount: zcp-system-admin
      serviceAccountName: zcp-system-admin
      terminationGracePeriodSeconds: 30
      tolerations:
      - effect: NoSchedule
        key: management
        operator: Equal
        value: "true"
      volumes:
      - emptyDir: {}
        name: elasticsearch-data
      - configMap:
          defaultMode: 420
          items:
          - key: client.yml
            path: elasticsearch.yml
          name: es-configmap
        name: elasticsearch-conf
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: 2020-03-30T01:45:53Z
    lastUpdateTime: 2020-03-30T01:45:53Z
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  observedGeneration: 1
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1
