apiVersion: v1
data:
  action_file.yml: |-
    ---
    actions:
      1:
        action: delete_indices
        description: "Clean up ES by deleting old indices"
        options:
          timeout_override:
          continue_if_exception: False
          disable_action: False
          ignore_empty_list: True
        filters:
        - filtertype: age
          source: name
          direction: older
          timestring: '%Y.%m.%d'
          unit: days
          unit_count: 10
          field:
          stats_result:
          epoch:
          exclude: False
  config.yml: |-
    ---
    client:
      hosts:
        - elasticsearch
      port: 9200
      url_prefix:
      use_ssl: False
      certificate:
      client_cert:
      client_key:
      ssl_no_validate: True
      http_auth:
      timeout: 30
      master_only: False
    logging:
      loglevel: INFO
      logfile:
      logformat: default
      blacklist: ['elasticsearch', 'urllib3']
kind: ConfigMap
metadata:
  creationTimestamp: 2019-05-13T09:11:03Z
  labels:
    app: elasticsearch-curator
    chart: elasticsearch-curator-1.5.0
    heritage: Tiller
    release: es-curator
  name: es-curator-elasticsearch-curator-config
  namespace: zcp-system
  resourceVersion: "19359981"
  selfLink: /api/v1/namespaces/zcp-system/configmaps/es-curator-elasticsearch-curator-config
  uid: 087a14f5-755f-11e9-98d4-1e7b3ccf7f43
