apiVersion: v1
data:
  client.yml: |-
    cluster.name: "elasticsearch-cluster"
    network.host: 0.0.0.0
    discovery.zen.ping.unicast.hosts: elasticsearch-discovery
    discovery.zen.minimum_master_nodes: 1
    node.master: false
    node.data: false
    xpack.security.enabled: false
    http:
      host: 0.0.0.0
      enabled: true
      compression: true
      cors:
        enabled: true
        allow-origin: "*"
    s3.client.default.endpoint: s3.seo-ap-geo.objectstorage.softlayer.net
  data.yml: |-
    cluster.name: "elasticsearch-cluster"
    network.host: 0.0.0.0
    discovery.zen.ping.unicast.hosts: elasticsearch-discovery
    discovery.zen.minimum_master_nodes: 1
    node.master: false
    node.data: true
    xpack.security.enabled: false
    http:
      host: 0.0.0.0
      enabled: true
      compression: true
      cors:
        enabled: true
        allow-origin: "*"
    s3.client.default.endpoint: s3.seo-ap-geo.objectstorage.softlayer.net
  master.yml: |-
    cluster.name: "elasticsearch-cluster"
    network.host: 0.0.0.0
    discovery.zen.ping.unicast.hosts: elasticsearch-discovery
    discovery.zen.minimum_master_nodes: 1
    node.master: true
    node.data: false
    xpack.security.enabled: false
    http:
      host: 0.0.0.0
      enabled: true
      compression: true
      cors:
        enabled: true
        allow-origin: "*"
    s3.client.default.endpoint: s3.seo-ap-geo.objectstorage.softlayer.net
kind: ConfigMap
metadata:
  creationTimestamp: 2020-03-30T01:45:53Z
  name: es-configmap
  namespace: zcp-system
  resourceVersion: "120198842"
  selfLink: /api/v1/namespaces/zcp-system/configmaps/es-configmap
  uid: 3f5e07bf-9f7d-4b8a-a6d5-05a4dbec2df9
