apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
  creationTimestamp: 2020-03-30T01:45:59Z
  generation: 1
  labels:
    app: fluentd-aggregator
    component: log-aggregator
  name: fluentd-aggregator
  namespace: zcp-system
  resourceVersion: "122805186"
  selfLink: /apis/extensions/v1beta1/namespaces/zcp-system/deployments/fluentd-aggregator
  uid: e2c9e6ca-0a61-4e19-a515-c595918a0b75
spec:
  minReadySeconds: 5
  progressDeadlineSeconds: 15
  replicas: 1
  revisionHistoryLimit: 5
  selector:
    matchLabels:
      app: fluentd-aggregator
      component: log-aggregator
  strategy:
    rollingUpdate:
      maxSurge: 100%
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: fluentd-aggregator
        component: log-aggregator
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: beta.kubernetes.io/arch
                operator: In
                values:
                - amd64
              - key: role
                operator: In
                values:
                - logging
      containers:
      - command:
        - fluentd
        - -c
        - /fluentd/etc/fluentd.conf
        - -p
        - /fluentd/plugins
        env:
        - name: FLUENTD_CONFIG
          value: fluentd-aggregator.conf
        image: registry.au-syd.bluemix.net/cloudzcp/fluentd:1.0.0-125
        imagePullPolicy: Always
        livenessProbe:
          failureThreshold: 3
          initialDelaySeconds: 5
          periodSeconds: 10
          successThreshold: 1
          tcpSocket:
            port: 24224
          timeoutSeconds: 1
        name: fluentd-aggregator
        ports:
        - containerPort: 24224
          name: fwd-input
          protocol: TCP
        - containerPort: 24224
          name: fwd-input-udp
          protocol: UDP
        - containerPort: 24231
          name: prom-metrics
          protocol: TCP
        - containerPort: 24220
          name: monitor-agent
          protocol: TCP
        - containerPort: 9880
          name: http-input
          protocol: TCP
        resources:
          limits:
            cpu: "2"
            memory: 1Gi
          requests:
            cpu: "1"
            memory: 250Mi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /fluentd/etc
          name: fluentd-config
      dnsPolicy: ClusterFirst
      imagePullSecrets:
      - name: bluemix-cloudzcp-secret
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      serviceAccount: zcp-system-admin
      serviceAccountName: zcp-system-admin
      terminationGracePeriodSeconds: 160
      tolerations:
      - effect: NoSchedule
        key: logging
        operator: Equal
        value: "true"
      volumes:
      - configMap:
          defaultMode: 420
          name: fluentd-config
        name: fluentd-config
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: 2020-03-30T01:45:59Z
    lastUpdateTime: 2020-03-30T01:46:17Z
    message: ReplicaSet "fluentd-aggregator-6c994b7598" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  - lastTransitionTime: 2020-04-07T10:20:47Z
    lastUpdateTime: 2020-04-07T10:20:47Z
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  observedGeneration: 1
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1
