apiVersion: v1
data:
  custom-filter.conf: "<filter kube.**.*earth1223** >\n  @type parser\n  key_name
    log\n  reserve_data true\n  reserve_time true\n  <parse>\n    @type json \n    #expression
    (?<apptime>^\\d{4}-\\d{2}-\\d{2} \\d{2}:\\d{2}:\\d{2},\\d{3})\\s\\[(?<thread>[a-zA-Z0-9-_]*)\\](?<restLog>.*)\n
    \   #time_key apptime \n    #time_format %Y-%m-%d %H:%M:%S,%L\n    #timezone +00:00\n
    \ </parse>\n</filter>\n"
kind: ConfigMap
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","data":{"custom-filter.conf":"\u003cfilter kube.**.*earth1223** \u003e\n  @type parser\n  key_name log\n  reserve_data true\n  reserve_time true\n  \u003cparse\u003e\n    @type json \n    #expression (?\u003capptime\u003e^\\d{4}-\\d{2}-\\d{2} \\d{2}:\\d{2}:\\d{2},\\d{3})\\s\\[(?\u003cthread\u003e[a-zA-Z0-9-_]*)\\](?\u003crestLog\u003e.*)\n    #time_key apptime \n    #time_format %Y-%m-%d %H:%M:%S,%L\n    #timezone +00:00\n  \u003c/parse\u003e\n\u003c/filter\u003e\n"},"kind":"ConfigMap","metadata":{"annotations":{},"labels":{"app":"fluentd"},"name":"fluentd-custom-config","namespace":"zcp-system"}}
  creationTimestamp: 2019-05-28T10:51:10Z
  labels:
    app: fluentd
  name: fluentd-custom-config
  namespace: zcp-system
