apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  creationTimestamp: 2020-03-30T02:24:07Z
  generation: 1
  labels:
    app: fluent-bit-logging
    kubernetes.io/cluster-service: "true"
    version: v1
  name: fluent-bit
  namespace: zcp-system
  resourceVersion: "122915709"
  selfLink: /apis/extensions/v1beta1/namespaces/zcp-system/daemonsets/fluent-bit
  uid: f5b70bdb-1e35-4bba-9bee-fa023fe471c5
spec:
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: fluent-bit-logging
      kubernetes.io/cluster-service: "true"
      version: v1
  template:
    metadata:
      annotations:
        prometheus.io/path: /api/v1/metrics/prometheus
        prometheus.io/port: "2020"
        prometheus.io/scrape: "true"
      creationTimestamp: null
      labels:
        app: fluent-bit-logging
        kubernetes.io/cluster-service: "true"
        version: v1
    spec:
      containers:
      - env:
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: spec.nodeName
        image: registry.au-syd.bluemix.net/cloudzcp/fluent-bit:0.13.4
        imagePullPolicy: Always
        name: fluent-bit
        ports:
        - containerPort: 2020
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /var/log
          name: varlog
        - mountPath: /var/data
          name: vardata
          readOnly: true
        - mountPath: /fluent-bit/etc/
          name: fluent-bit-config
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      serviceAccount: zcp-system-admin
      serviceAccountName: zcp-system-admin
      terminationGracePeriodSeconds: 10
      tolerations:
      - operator: Exists
      volumes:
      - hostPath:
          path: /var/log
          type: ""
        name: varlog
      - hostPath:
          path: /var/data
          type: ""
        name: vardata
      - configMap:
          defaultMode: 420
          name: fluent-bit-config
        name: fluent-bit-config
  templateGeneration: 1
  updateStrategy:
    type: OnDelete
status:
  currentNumberScheduled: 13
  desiredNumberScheduled: 13
  numberAvailable: 13
  numberMisscheduled: 0
  numberReady: 13
  observedGeneration: 1
  updatedNumberScheduled: 13
