apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
  creationTimestamp: 2020-03-30T01:27:29Z
  generation: 1
  labels:
    app: kibana
    component: kibana
  name: kibana
  namespace: zcp-system
  resourceVersion: "122805169"
  selfLink: /apis/extensions/v1beta1/namespaces/zcp-system/deployments/kibana
  uid: 2e8117da-b8a9-4d7c-b620-3475fb915dae
spec:
  progressDeadlineSeconds: 2147483647
  replicas: 1
  revisionHistoryLimit: 2147483647
  selector:
    matchLabels:
      app: kibana
      component: kibana
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: kibana
        component: kibana
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: beta.kubernetes.io/arch
                operator: In
                values:
                - amd64
              - key: role
                operator: In
                values:
                - logging
      containers:
      - image: registry.au-syd.bluemix.net/cloudzcp/kibana:6.3.1
        imagePullPolicy: IfNotPresent
        name: kibana
        ports:
        - containerPort: 5602
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /usr/share/kibana/config/kibana.yml
          name: kibana-conf
          subPath: kibana.yml
        - mountPath: /usr/share/kibana/optimize
          name: cache
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      serviceAccount: zcp-system-admin
      serviceAccountName: zcp-system-admin
      terminationGracePeriodSeconds: 30
      tolerations:
      - effect: NoSchedule
        key: logging
        operator: Equal
        value: "true"
      volumes:
      - emptyDir: {}
        name: cache
      - configMap:
          defaultMode: 420
          items:
          - key: kibana.yml
            path: kibana.yml
          name: kibana-config
        name: kibana-conf
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: 2020-03-30T01:27:29Z
    lastUpdateTime: 2020-03-30T01:27:29Z
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  observedGeneration: 1
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1
