apiVersion: v1
kind: Service
metadata:
  name: springboot-modern-template
spec:
  ports:
  - name: "http"
    port: 8080
    targetPort: 8080
  selector:
    app: springboot-modern-template
  type: NodePort
