spring:
  application:
    name: redis-cache-pattern
  redis:
    port: 6379
    host: localhost
    password: hjlee9854
    lettuce:
      pool:
        max-active: 10
        max-idle: 10
        min-idle: 2
        max-wait: 30
    database: 0

  cache:
    type: redis
    redis:
      defaultExpireTime: 600
      time-to-live: 60
      key-prefix: "myCache_"
      use-key-prefix: true

server:
  port: 8082
