spring:
  application:
    name: order-service
  datasource:
    dbcp2:
      initial-size: 20
    url: jdbc:mariadb://mariadb.twolinecode.com/modern_pattern?autoReconnect=true&useSSL=false
    driver-class-name: org.mariadb.jdbc.Driver
    username: root
    password: tlc19#
    initialization-mode: always
  mvc:
    throw-exception-if-no-handler-found: true
  jackson:
    date-format: "yyyy-MM-dd'T'HH:mm:ss"
  profiles:
    active: mariadb

  jpa:
    hibernate:
      ddl-auto: create
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        show-sql: true
        use_sql_comments: true
        format_sql: true
    open-in-view: false
    generate-ddl: true
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    database: mysql

server:
  port: 8000
