spring:
  application:
    name: redis-cache-pattern
  redis:
    lettuce:
      pool:
        max-active: 10
        max-idle: 10
        min-idle: 2
        max-wait: 30
    database: 0

  cache:
    redis:
      defaultExpireTime: 600
      time-to-live: 60
      key-prefix: "myCache_"
      use-key-prefix: true

server:
  port: 8082

info:
    name: ${spring.application.name}
    description: springboot-redis-cache-pattern demo
    environment: ${spring.profiles.active}
    version: 0.0.1