apiVersion: apps/v1
kind: Deployment
metadata:
  name: springboot-redis-cache-pattern
  labels:
    app: springboot-redis-cache-pattern
spec:
  replicas: 1
  selector:
    matchLabels:
      app: springboot-redis-cache-pattern
  template:
    metadata:
      labels:
        app: springboot-redis-cache-pattern
    spec:
      containers:
      - name: springboot-redis-cache-pattern
        image: han/springboot-redis-cache-pattern:0.0.1
        ports:
        - containerPort: 8082
        imagePullPolicy: Always
        resources:
          requests:
            memory: 128Mi            
          limits:
            memory: 256Mi
        envFrom:
          - configMapRef:
              name: springboot-redis-cache-pattern-kv-config
        volumeMounts:
          - mountPath: /config
            name: springboot-redis-cache-pattern-config-volume
            readOnly: true
      volumes:
        - name: springboot-redis-cache-pattern-config-volume
          configMap:
            name: springboot-redis-cache-pattern-config
            items:
              - key: application.yaml
                path: application.yaml
              - key: application-overlay.yaml
                # 최종적으로 /config/overlay/application.yaml 에 위치
                # 이 property를 참조하기 위한 설정은 base/kustomization.yaml에 있다.
                path: overlay/application.yaml

