apiVersion: v1
kind: Service
metadata:
  name: circuit-breaker-bookstore
spec:
  ports:
  - name: "http"
    port: 8080
    targetPort: 8080
  selector:
    app: circuit-breaker-bookstore
  type: NodePort
