{
 "title": "Circuit Breaker",
 "description": "Circuit Breaker",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "application", "label": "Application", "query": "label_values(application)" },
   {
    "name": "app",
    "label": "app",
    "query": "label_values(resilience4j_circuitbreaker_state, app)"
   },
   {
    "name": "circuitbreaker_name",
    "label": "CircuitBreaker Name",
    "query": "label_values(resilience4j_circuitbreaker_state, name)"
   },
   {
    "name": "retry_name",
    "label": "Retry Name",
    "query": "label_values(resilience4j_retry_calls, name)"
   },
   {
    "name": "bulkhead_name",
    "label": "Bulkhead Name",
    "query": "label_values(resilience4j_bulkhead_available_concurrent_calls, name)"
   }
  ]
 },
 "panels": [
  { "title": "Summary", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Number of open CircuitBreaker",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(resilience4j_circuitbreaker_state{state=~\"open|forced_open\"})"
    }
   ]
  },
  {
   "title": "Number of half_open CircuitBreaker",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(resilience4j_circuitbreaker_state{state=\"half_open\"})"
    }
   ]
  },
  {
   "title": "Number of closed CircuitBreaker",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(resilience4j_circuitbreaker_state{state=\"closed\"})"
    }
   ]
  },
  {
   "title": "CircuitBreaker States",
   "type": "graph",
   "gridPos": { "h": 14, "w": 24, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "short", "label": "Number" }
   ],
   "targets": [
    {
     "expr": "resilience4j_circuitbreaker_state{app=~\"$app\"}",
     "legendFormat": "{{ application }}: {{ name }}: {{ state }}"
    }
   ]
  },
  {
   "title": "CircuitBreaker",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 },
   "repeat": "circuitbreaker_name",
   "collapsed": true,
   "panels": [
    {
     "title": "Failure Rate: $circuitbreaker_name",
     "type": "singlestat",
     "gridPos": { "h": 7, "w": 6, "x": 0, "y": 2 },
     "format": "percent",
     "valueName": "current",
     "targets": [
      {
       "expr": "resilience4j_circuitbreaker_failure_rate{app=~\"$app\",name=~\"$circuitbreaker_name\"}",
       "legendFormat": "{{ name }}"
      }
     ]
    },
    {
     "title": "Buffered calls: $circuitbreaker_name",
     "type": "graph",
     "gridPos": { "h": 7, "w": 18, "x": 6, "y": 2 },
     "yaxes": [
      { "format": "short", "label": "Number" }
     ],
     "targets": [
      {
       "expr": "resilience4j_circuitbreaker_failure_rate{app=~\"$app\",name=~\"$circuitbreaker_name\"}",
       "legendFormat": "{{name}}"
      }
     ]
    },
    {
     "title": "Call rate: $circuitbreaker_name",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
     "yaxes": [
      { "format": "short", "label": "Calls/sec" }
     ],
     "targets": [
      {
       "expr": "rate(resilience4j_circuitbreaker_calls_seconds_count{app=~\"$app\",name=~\"$circuitbreaker_name\"}[1m])",
       "legendFormat": "{{ kind }} "
      },
      {
       "expr": "rate(resilience4j_circuitbreaker_calls_total{app=~\"$app\",name=~\"$circuitbreaker_name\"}[1m])",
       "legendFormat": "{{ kind  }} "
      }
     ]
    },
    {
     "title": "Buffered calls: $circuitbreaker_name",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
     "yaxes": [
      { "format": "short", "label": "Number" }
     ],
     "targets": [
      {
       "expr": "resilience4j_circuitbreaker_buffered_calls{app=~\"$app\",name=~\"$circuitbreaker_name\"}",
       "legendFormat": "{{ kind }}"
      },
      {
       "expr": "resilience4j_circuitbreaker_max_buffered_calls{app=~\"$app\",name=~\"$circuitbreaker_name\"}",
       "legendFormat": "maximum"
      }
     ]
    },
    {
     "title": "Call duration percentiles",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 17 },
     "yaxes": [
      { "format": "s", "label": "Average duration" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.9, sum(rate(resilience4j_circuitbreaker_calls_seconds_bucket{application=~\"$application\", app=~\"$app\", name=~\"$circuitbreaker_name\"}[1m])) by (le))",
       "legendFormat": "90th Percentile"
      },
      {
       "expr": "histogram_quantile(0.95, sum(rate(resilience4j_circuitbreaker_calls_seconds_bucket{application=~\"$application\", app=~\"$app\", name=~\"$circuitbreaker_name\"}[1m])) by (le))",
       "legendFormat": "95th Percentile"
      },
      {
       "expr": "histogram_quantile(0.98, sum(rate(resilience4j_circuitbreaker_calls_seconds_bucket{application=~\"$application\", app=~\"$app\", name=~\"$circuitbreaker_name\"}[1m])) by (le))",
       "legendFormat": "98th Percentile"
      },
      {
       "expr": "histogram_quantile(0.50, sum(rate(resilience4j_circuitbreaker_calls_seconds_bucket{application=~\"$application\", app=~\"$app\", name=~\"$circuitbreaker_name\"}[1m])) by (le))",
       "legendFormat": "Median"
      }
     ]
    },
    {
     "title": "Average call durations",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 17 },
     "yaxes": [
      { "format": "s", "label": "Average duration" }
     ],
     "targets": [
      {
       "expr": "increase(resilience4j_circuitbreaker_calls_seconds_sum{app=~\"$app\",name=~\"$circuitbreaker_name\"}[1m]) / increase(resilience4j_circuitbreaker_calls_seconds_count{app=~\"$app\",name=~\"$circuitbreaker_name\"}[1m])",
       "legendFormat": "{{ kind }}"
      },
      {
       "expr": "sum(increase(resilience4j_circuitbreaker_calls_seconds_sum{app=~\"$app\",name=~\"$circuitbreaker_name\"}[1m])) / sum(increase(resilience4j_circuitbreaker_calls_seconds_count{app=~\"$app\",name=~\"$circuitbreaker_name\"}[1m]))",
       "legendFormat": "total "
      }
     ]
    }
   ]
  },
  {
   "title": "Retry",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 },
   "repeat": "retry_name",
   "collapsed": true,
   "panels": [
    {
     "title": "Rate retryable calls: $retry_name",
     "type": "graph",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 25 },
     "yaxes": [
      { "format": "short", "label": "Number of calls" }
     ],
     "targets": [
      {
       "expr": "rate(resilience4j_retry_calls{application=~\"$application\",name=~\"$retry_name\",}[1m])",
       "legendFormat": "{{ kind }}"
      }
     ]
    }
   ]
  },
  {
   "title": "Bulkhead",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 },
   "repeat": "bulkhead_name",
   "collapsed": true,
   "panels": [
    {
     "title": "Bulkhead: $bulkhead_name",
     "type": "graph",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 26 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "resilience4j_bulkhead_available_concurrent_calls{application=~\"$application\",name=~\"$bulkhead_name\"}",
       "legendFormat": "Available Calls"
      },
      {
       "expr": "resilience4j_bulkhead_max_allowed_concurrent_calls{application=~\"$application\",name=~\"$bulkhead_name\"}",
       "legendFormat": "Max allowed Calls"
      }
     ]
    }
   ]
  }
 ]
}