server: 
  port: 8083

spring:
  application:
    name: spring-boot-rabbitmq

#  servlet: 
#    multipart:
#      max-file-size: 256MB
#      max-request-size: 256MB
#      enabled: true

  rabbitmq:
    host: ${spring.rabbitmq.host}
    port: ${spring.rabbitmq.port}
    username: ${spring.rabbitmq.username}
    password: ${spring.rabbitmq.password}
    virtual-host: ${spring.rabbitmq.virtualhost}
  
  cloud: 
    stream: 
      bindings: 
        output: 
          destination: mydestination
          # binder: rabbit
        input:
          destination: mydestination
          # binder: rabbit
      defaultBinder: rabbit

  amazonmq:
    host: ${spring.amazonmq.host}
    port: ${spring.amazonmq.port}
    username: ${spring.amazonmq.username}
    password: ${spring.amazonmq.pasword}

logging: 
  level: 
    org: 
      springframework: 
        cloud: 
          stream: debug

