spring:
  application:
    name: redis-session-pattern
  redis:
    lettuce:
      pool:
        max-active: 10
        max-idle: 10
        min-idle: 2
        max-wait: 30
    database: 0
    channel: mychannel

  session:
    redis:
      flush-mode: on_save
      save-mode: always
      namespace: spring:test

  cache:
    redis:
      defaultExpireTime: 60
      expireTime:
        billDetailData: 3600
        billSummaryInfos: 3600
      time-to-live: 60
      key-prefix: "MyKey"
      use-key-prefix: true
    cache-names: "MyCacheNames1"

server:
  port: 8082

info:
    name: ${spring.application.name}
    description: springboot-redis-pattern demo
    environment: ${spring.profiles.active}
    version: 0.0.1