apiVersion: v1
kind: Service
metadata:
  name: springboot-redis-session-pattern
spec:
  ports:
  - name: "http"
    port: 8082
    targetPort: 8082
  selector:
    app: springboot-redis-session-pattern
  type: NodePort
