apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "25"
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"extensions/v1beta1","kind":"Deployment","metadata":{"annotations":{},"name":"alertmanager","namespace":"zcp-system"},"spec":{"replicas":1,"selector":{"matchLabels":{"component":"alertmanager"}},"template":{"metadata":{"labels":{"component":"alertmanager"},"name":"alertmanager"},"spec":{"affinity":{"nodeAffinity":{"requiredDuringSchedulingIgnoredDuringExecution":{"nodeSelectorTerms":[{"matchExpressions":[{"key":"beta.kubernetes.io/arch","operator":"In","values":["amd64"]},{"key":"node-role.kubernetes.io/management","operator":"Exists"}]}]}}},"containers":[{"args":["--config.file=/etc/config/alertmanager.yml","--storage.path=/data"],"image":"au.icr.io/cloudzcp/alertmanager:v0.20.0","livenessProbe":{"failureThreshold":3,"httpGet":{"path":"/-/healthy","port":9093,"scheme":"HTTP"},"initialDelaySeconds":30,"periodSeconds":10,"successThreshold":1,"timeoutSeconds":30},"name":"alertmanager","ports":[{"containerPort":9093,"name":"alertmanager","protocol":"TCP"}],"readinessProbe":{"failureThreshold":3,"httpGet":{"path":"/-/ready","port":9093,"scheme":"HTTP"},"initialDelaySeconds":30,"periodSeconds":10,"successThreshold":1,"timeoutSeconds":30},"resources":{"limits":{"cpu":"10m","memory":"50Mi"},"requests":{"cpu":"10m","memory":"50Mi"}},"volumeMounts":[{"mountPath":"/etc/config","name":"config-volume"},{"mountPath":"/data","name":"storage-volume"},{"mountPath":"/etc/templates","name":"templates-volume"},{"mountPath":"/etc/secrets","name":"secrets-volume","readOnly":true,"subPath":""}]}],"restartPolicy":"Always","serviceAccountName":"zcp-system-admin","tolerations":[{"effect":"NoSchedule","key":"management","operator":"Equal","value":"true"}],"volumes":[{"configMap":{"name":"alertmanager"},"name":"config-volume"},{"emptyDir":{},"name":"storage-volume"},{"configMap":{"name":"alertmanager-templates"},"name":"templates-volume"},{"name":"secrets-volume","secret":{"secretName":"alertmanager-secret"}}]}}}}
  creationTimestamp: 2019-02-26T06:05:46Z
  generation: 38
  labels:
    component: alertmanager
  name: alertmanager
  namespace: zcp-system
  resourceVersion: "117108381"
  selfLink: /apis/extensions/v1beta1/namespaces/zcp-system/deployments/alertmanager
  uid: 8ee7425d-398c-11e9-814c-ca0890826a6e
spec:
  progressDeadlineSeconds: 2147483647
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      component: alertmanager
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        component: alertmanager
      name: alertmanager
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: beta.kubernetes.io/arch
                operator: In
                values:
                - amd64
              - key: node-role.kubernetes.io/management
                operator: Exists
      containers:
      - args:
        - --config.file=/etc/config/alertmanager.yml
        - --storage.path=/data
        image: au.icr.io/cloudzcp/alertmanager:v0.20.0
        imagePullPolicy: IfNotPresent
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /-/healthy
            port: 9093
            scheme: HTTP
          initialDelaySeconds: 30
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 30
        name: alertmanager
        ports:
        - containerPort: 9093
          name: alertmanager
          protocol: TCP
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /-/ready
            port: 9093
            scheme: HTTP
          initialDelaySeconds: 30
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 30
        resources:
          limits:
            cpu: 10m
            memory: 50Mi
          requests:
            cpu: 10m
            memory: 50Mi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /etc/config
          name: config-volume
        - mountPath: /data
          name: storage-volume
        - mountPath: /etc/templates
          name: templates-volume
        - mountPath: /etc/secrets
          name: secrets-volume
          readOnly: true
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      serviceAccount: zcp-system-admin
      serviceAccountName: zcp-system-admin
      terminationGracePeriodSeconds: 30
      tolerations:
      - effect: NoSchedule
        key: management
        operator: Equal
        value: "true"
      volumes:
      - configMap:
          defaultMode: 420
          name: alertmanager
        name: config-volume
      - emptyDir: {}
        name: storage-volume
      - configMap:
          defaultMode: 420
          name: alertmanager-templates
        name: templates-volume
      - name: secrets-volume
        secret:
          defaultMode: 420
          secretName: alertmanager-secret
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: 2019-02-26T06:05:46Z
    lastUpdateTime: 2019-02-26T06:05:46Z
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  observedGeneration: 38
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1
