apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "7"
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"apps/v1beta1","kind":"Deployment","metadata":{"annotations":{},"name":"blackbox-exporter","namespace":"zcp-system"},"spec":{"replicas":1,"selector":{"matchLabels":{"component":"blackbox-exporter"}},"template":{"metadata":{"labels":{"component":"blackbox-exporter"}},"spec":{"affinity":{"nodeAffinity":{"requiredDuringSchedulingIgnoredDuringExecution":{"nodeSelectorTerms":[{"matchExpressions":[{"key":"beta.kubernetes.io/arch","operator":"In","values":["amd64"]},{"key":"node-role.kubernetes.io/management","operator":"Exists"}]}]}}},"containers":[{"args":["--config.file=/etc/config/blackbox.yml"],"image":"au.icr.io/cloudzcp/blackbox-exporter:v0.16.0","name":"blackbox-exporter","ports":[{"containerPort":9115,"name":"metrics"}],"resources":{"limits":{"cpu":"10m","memory":"50Mi"},"requests":{"cpu":"5m","memory":"25Mi"}},"volumeMounts":[{"mountPath":"/etc/config/","name":"blackbox-config-volume"}]}],"restartPolicy":"Always","tolerations":[{"effect":"NoSchedule","key":"management","operator":"Equal","value":"true"}],"volumes":[{"configMap":{"defaultMode":420,"name":"blackbox-exporter-config"},"name":"blackbox-config-volume"}]}}}}
  creationTimestamp: 2019-02-26T06:05:27Z
  generation: 12
  labels:
    component: blackbox-exporter
  name: blackbox-exporter
  namespace: zcp-system
  resourceVersion: "117143110"
  selfLink: /apis/extensions/v1beta1/namespaces/zcp-system/deployments/blackbox-exporter
  uid: 83a78ea5-398c-11e9-b959-fafab1df8288
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      component: blackbox-exporter
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        component: blackbox-exporter
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: beta.kubernetes.io/arch
                operator: In
                values:
                - amd64
              - key: node-role.kubernetes.io/management
                operator: Exists
      containers:
      - args:
        - --config.file=/etc/config/blackbox.yml
        image: au.icr.io/cloudzcp/blackbox-exporter:v0.16.0
        imagePullPolicy: IfNotPresent
        name: blackbox-exporter
        ports:
        - containerPort: 9115
          name: metrics
          protocol: TCP
        resources:
          limits:
            cpu: 10m
            memory: 50Mi
          requests:
            cpu: 5m
            memory: 25Mi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /etc/config/
          name: blackbox-config-volume
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      tolerations:
      - effect: NoSchedule
        key: management
        operator: Equal
        value: "true"
      volumes:
      - configMap:
          defaultMode: 420
          name: blackbox-exporter-config
        name: blackbox-config-volume
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: 2020-03-12T14:05:12Z
    lastUpdateTime: 2020-03-12T14:05:12Z
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  - lastTransitionTime: 2019-02-26T06:05:27Z
    lastUpdateTime: 2020-03-20T09:30:19Z
    message: ReplicaSet "blackbox-exporter-5d97dd67b9" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  observedGeneration: 12
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1
