apiVersion: v1
data:
  GF_AUTH_GENERIC_OAUTH_AUTH_URL: https://pog-dev-iam.cloudzcp.io/auth/realms/zcp/protocol/openid-connect/auth
  GF_SERVER_DOMAIN: pog-dev-monitoring.cloudzcp.io
  grafana.ini: |-
    app_mode = production
    instance_name = ${HOSTNAME}
    [paths]
    data = /var/lib/grafana/data
    logs = /var/log/grafana
    plugins = /var/lib/grafana/plugins
    provisioning = /etc/grafana/provisioning

    [server]
    protocol = http
    http_port = 3000
    ;domain = base-monitoring.cloudzcp.io
    enforce_domain = true
    root_url = https://%(domain)s/
    ;router_logging = false
    ;static_root_path = public
    ;enable_gzip = false
    ;cert_file =
    ;cert_key =

    [database]
    ;type = sqlite3
    ;host = 127.0.0.1:3306
    ;name = grafana
    ;user = root
    ;password =
    ;ssl_mode = disable
    ;path = grafana.db

    [session]
    ;provider = file
    ;provider_config = sessions
    ;cookie_name = grafana_sess
    ;cookie_secure = false
    ;session_life_time = 86400

    [analytics]
    ;reporting_enabled = true
    check_for_updates = true
    ;google_analytics_ua_id =

    [security]
    ;admin_user = admin
    ;admin_password = admin
    ;secret_key = SW2YcwTIb9zpOOhoPsMm
    ;login_remember_days = 7
    ;cookie_username = grafana_user
    ;cookie_remember_name = grafana_remember
    ;disable_gravatar = false
    ;data_source_proxy_whitelist =

    [snapshots]
    ;external_enabled = true
    ;external_snapshot_url = https://snapshots-origin.raintank.io
    ;external_snapshot_name = Publish to snapshot.raintank.io

    [users]
    ;allow_sign_up = true
    ;allow_org_create = true
    ;auto_assign_org = true
    ;auto_assign_org_role = Viewer
    ;login_hint = email or username
    default_theme = light

    [auth.anonymous]
    ;enabled = true
    ;org_name = Main Org.
    ;org_role = Admin

    [auth.github]
    ;enabled = false
    ;allow_sign_up = false
    ;client_id = some_id
    ;client_secret = some_secret
    ;scopes = user:email,read:org
    ;auth_url = https://github.com/login/oauth/authorize
    ;token_url = https://github.com/login/oauth/access_token
    ;api_url = https://api.github.com/user
    ;team_ids =
    ;allowed_organizations =

    [auth.google]
    ;enabled = false
    ;allow_sign_up = false
    ;client_id = some_client_id
    ;client_secret = some_client_secret
    ;scopes = https://www.googleapis.com/auth/userinfo.profile https://www.googleapis.com/auth/userinfo.email
    ;auth_url = https://accounts.google.com/o/oauth2/auth
    ;token_url = https://accounts.google.com/o/oauth2/token
    ;api_url = https://www.googleapis.com/oauth2/v1/userinfo
    ;allowed_domains =

    [auth.proxy]
    ;enabled = false
    ;header_name = X-WEBAUTH-USER
    ;header_property = username
    ;auto_sign_up = true

    [auth.generic_oauth]
    name = OAuth
    enabled = true
    allow_sign_up = true
    client_id = monitoring
    client_secret = 4138cbf9-4091-4029-a1d6-d64450994f55
    scopes = openid email name
    ;auth_url = https://base-iam.cloudzcp.io/auth/realms/zcp/protocol/openid-connect/auth
    token_url = http://zcp-oidc-keycloak-http:80/auth/realms/zcp/protocol/openid-connect/token
    ;api_url =
    ;team_ids =
    ;allowed_organizations =

    [auth.basic]
    ;enabled = true

    [auth.ldap]
    ;enabled = false
    ;config_file = /etc/grafana/ldap.toml

    [smtp]
    ;enabled = false
    ;host = localhost:25
    ;user =
    ;password =
    ;cert_file =
    ;key_file =
    ;skip_verify = false
    ;from_address = admin@grafana.localhost

    [emails]
    ;welcome_email_on_sign_up = false

    [log]
    mode = console
    level = info

    [log.console]
    ;level =
    ;format = console

    [event_publisher]
    ;enabled = false
    ;rabbitmq_url = amqp://localhost/
    ;exchange = grafana_events

    [dashboards.json]
    ;enabled = true
    ;path = /etc/dashboards

    [metrics]
    enabled           = true
    interval_seconds  = 10

    ; [metrics.graphite]
    ; address = localhost:2003
    ; prefix = prod.grafana.%(instance_name)s.

    [grafana_com]
    url = https://grafana.com
kind: ConfigMap
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","data":{"GF_AUTH_GENERIC_OAUTH_AUTH_URL":"https://pog-dev-iam.cloudzcp.io/auth/realms/zcp/protocol/openid-connect/auth","GF_SERVER_DOMAIN":"pog-dev-monitoring.cloudzcp.io","grafana.ini":"app_mode = production\ninstance_name = ${HOSTNAME}\n[paths]\ndata = /var/lib/grafana/data\nlogs = /var/log/grafana\nplugins = /var/lib/grafana/plugins\nprovisioning = /etc/grafana/provisioning\n\n[server]\nprotocol = http\nhttp_port = 3000\n;domain = base-monitoring.cloudzcp.io\nenforce_domain = true\nroot_url = https://%(domain)s/\n;router_logging = false\n;static_root_path = public\n;enable_gzip = false\n;cert_file =\n;cert_key =\n\n[database]\n;type = sqlite3\n;host = 127.0.0.1:3306\n;name = grafana\n;user = root\n;password =\n;ssl_mode = disable\n;path = grafana.db\n\n[session]\n;provider = file\n;provider_config = sessions\n;cookie_name = grafana_sess\n;cookie_secure = false\n;session_life_time = 86400\n\n[analytics]\n;reporting_enabled = true\ncheck_for_updates = true\n;google_analytics_ua_id =\n\n[security]\n;admin_user = admin\n;admin_password = admin\n;secret_key = SW2YcwTIb9zpOOhoPsMm\n;login_remember_days = 7\n;cookie_username = grafana_user\n;cookie_remember_name = grafana_remember\n;disable_gravatar = false\n;data_source_proxy_whitelist =\n\n[snapshots]\n;external_enabled = true\n;external_snapshot_url = https://snapshots-origin.raintank.io\n;external_snapshot_name = Publish to snapshot.raintank.io\n\n[users]\n;allow_sign_up = true\n;allow_org_create = true\n;auto_assign_org = true\n;auto_assign_org_role = Viewer\n;login_hint = email or username\ndefault_theme = light\n\n[auth.anonymous]\n;enabled = true\n;org_name = Main Org.\n;org_role = Admin\n\n[auth.github]\n;enabled = false\n;allow_sign_up = false\n;client_id = some_id\n;client_secret = some_secret\n;scopes = user:email,read:org\n;auth_url = https://github.com/login/oauth/authorize\n;token_url = https://github.com/login/oauth/access_token\n;api_url = https://api.github.com/user\n;team_ids =\n;allowed_organizations =\n\n[auth.google]\n;enabled = false\n;allow_sign_up = false\n;client_id = some_client_id\n;client_secret = some_client_secret\n;scopes = https://www.googleapis.com/auth/userinfo.profile https://www.googleapis.com/auth/userinfo.email\n;auth_url = https://accounts.google.com/o/oauth2/auth\n;token_url = https://accounts.google.com/o/oauth2/token\n;api_url = https://www.googleapis.com/oauth2/v1/userinfo\n;allowed_domains =\n\n[auth.proxy]\n;enabled = false\n;header_name = X-WEBAUTH-USER\n;header_property = username\n;auto_sign_up = true\n\n[auth.generic_oauth]\nname = OAuth\nenabled = true\nallow_sign_up = true\nclient_id = monitoring\nclient_secret = 4138cbf9-4091-4029-a1d6-d64450994f55\nscopes = openid email name\n;auth_url = https://base-iam.cloudzcp.io/auth/realms/zcp/protocol/openid-connect/auth\ntoken_url = http://zcp-oidc-keycloak-http:80/auth/realms/zcp/protocol/openid-connect/token\n;api_url =\n;team_ids =\n;allowed_organizations =\n\n[auth.basic]\n;enabled = true\n\n[auth.ldap]\n;enabled = false\n;config_file = /etc/grafana/ldap.toml\n\n[smtp]\n;enabled = false\n;host = localhost:25\n;user =\n;password =\n;cert_file =\n;key_file =\n;skip_verify = false\n;from_address = admin@grafana.localhost\n\n[emails]\n;welcome_email_on_sign_up = false\n\n[log]\nmode = console\nlevel = info\n\n[log.console]\n;level =\n;format = console\n\n[event_publisher]\n;enabled = false\n;rabbitmq_url = amqp://localhost/\n;exchange = grafana_events\n\n[dashboards.json]\nenabled = true\npath = /etc/dashboards\n\n[metrics]\nenabled           = true\ninterval_seconds  = 10\n\n; [metrics.graphite]\n; address = localhost:2003\n; prefix = prod.grafana.%(instance_name)s.\n\n[grafana_com]\nurl = https://grafana.com"},"kind":"ConfigMap","metadata":{"annotations":{},"labels":{},"name":"monitoring-grafana-config","namespace":"zcp-system"}}
  creationTimestamp: 2019-02-26T06:05:38Z
  labels:
    component: grafana
  name: monitoring-grafana-config
  namespace: zcp-system
  resourceVersion: "118272976"
  selfLink: /api/v1/namespaces/zcp-system/configmaps/monitoring-grafana-config
  uid: 8a270339-398c-11e9-b959-fafab1df8288
