{
 "title": "Etcd Cluster",
 "description": "Etcd Dashboard for Prometheus metrics scraper",
 "tags": [
  "kubernetes",
  "etcd"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Etcd has a leader?",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    { "expr": "max(etcd_server_has_leader)" }
   ]
  },
  {
   "title": "The number of leader changes seen",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "max(etcd_server_leader_changes_seen_total)"
    }
   ]
  },
  {
   "title": "The total number of failed proposals seen",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "max(etcd_server_proposals_failed_total)"
    }
   ]
  },
  {
   "title": "RPC Rate",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum(rate(grpc_server_started_total{grpc_type=\"unary\"}[5m]))",
     "legendFormat": "RPC Rate"
    },
    {
     "expr": "sum(rate(grpc_server_handled_total{grpc_type=\"unary\",grpc_code!=\"OK\"}[5m]))",
     "legendFormat": "RPC Failed Rate"
    }
   ]
  },
  {
   "title": "DB Size",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 13 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "etcd_debugging_mvcc_db_total_size_in_bytes",
     "legendFormat": "{{instance}} DB Size"
    }
   ]
  },
  {
   "title": "Disk Sync Duration",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 13 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(etcd_disk_wal_fsync_duration_seconds_bucket[5m])) by (instance, le))",
     "legendFormat": "{{instance}} WAL fsync"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(etcd_disk_backend_commit_duration_seconds_bucket[5m])) by (instance, le))",
     "legendFormat": "{{instance}} DB fsync"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 13 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "process_resident_memory_bytes{job='etcd'}",
     "legendFormat": "{{instance}} Resident Memory"
    }
   ]
  },
  {
   "title": "Client Traffic In",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 20 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(etcd_network_client_grpc_received_bytes_total[5m])",
     "legendFormat": "{{instance}} Client Traffic In"
    }
   ]
  },
  {
   "title": "Client Traffic Out",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 20 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "rate(etcd_network_client_grpc_sent_bytes_total[5m])",
     "legendFormat": "{{instance}} Client Traffic Out"
    }
   ]
  },
  {
   "title": "Peer Traffic In",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 20 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(etcd_network_peer_received_bytes_total[5m])) by (instance)",
     "legendFormat": "{{instance}} Peer Traffic In"
    }
   ]
  },
  {
   "title": "Peer Traffic Out",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 20 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(etcd_network_peer_sent_bytes_total[5m])) by (instance)",
     "legendFormat": "{{instance}} Peer Traffic Out"
    }
   ]
  },
  {
   "title": "prometheus Proposals",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 27 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(etcd_server_proposals_failed_total[5m]))",
     "legendFormat": "Proposal Failure Rate"
    },
    {
     "expr": "sum(etcd_server_proposals_pending)",
     "legendFormat": "Proposal Pending Total"
    },
    {
     "expr": "sum(rate(etcd_server_proposals_committed_total[5m]))",
     "legendFormat": "Proposal Commit Rate"
    },
    {
     "expr": "sum(rate(etcd_server_proposals_applied_total[5m]))",
     "legendFormat": "Proposal Apply Rate"
    }
   ]
  },
  {
   "title": "Disks operations",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 34 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum(rate(etcd_disk_wal_fsync_duration_seconds_sum[2m]))",
     "legendFormat": "The latency distributions of fsync called by wal"
    },
    {
     "expr": "sum(rate(etcd_disk_backend_commit_duration_seconds_sum[2m]))",
     "legendFormat": "The latency distributions of commit called by backend"
    }
   ]
  },
  {
   "title": "Network",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 41 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(etcd_network_client_grpc_received_bytes_total[2m]))",
     "legendFormat": "The total number of bytes received by grpc clients"
    },
    {
     "expr": "sum(rate(etcd_network_client_grpc_sent_bytes_total[2m]))",
     "legendFormat": "The total number of bytes sent to grpc clients"
    }
   ]
  },
  {
   "title": "Snapshot duration",
   "type": "graph",
   "description": "Abnormally high snapshot duration (snapshot_save_total_duration_seconds) indicates disk issues and might cause the cluster to be unstable.",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 48 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum(rate(etcd_debugging_snap_save_total_duration_seconds_sum[2m]))",
     "legendFormat": "The total latency distributions of save called by snapshot"
    }
   ]
  }
 ]
}
{
 "title": "Kubernetes: Cluster Overview",
 "tags": [ "kubernetes" ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "node",
    "label": "node",
    "query": "label_values(kube_node_labels, node)"
   }
  ]
 },
 "panels": [
  { "title": "Resource Dashboard", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Alerts Firing",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(ALERTS{alertstate=\"firing\",alertname!=\"DeadMansSwitch\"})"
    }
   ]
  },
  {
   "title": "Node Not Ready",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 6, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(kube_node_status_condition{condition=\"Ready\",status!=\"true\"})"
    }
   ]
  },
  {
   "title": "Nodes Unschedulable",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(kube_node_spec_unschedulable)"
    }
   ]
  },
  {
   "title": "Node Memory Pressure",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(kube_node_status_condition{condition=\"MemoryPressure\",status=\"true\"})"
    }
   ]
  },
  {
   "title": "Node Disk Pressure",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(kube_node_status_condition{condition=\"DiskPressure\",status=\"true\"})"
    }
   ]
  },
  {
   "title": "Running Pod",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 12, "x": 0, "y": 4 },
   "format": "none",
   "valueName": "current",
   "targets": [
    { "expr": "sum(kubelet_running_pod_count)" }
   ]
  },
  {
   "title": "Running Container",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 12, "x": 12, "y": 4 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(kubelet_running_container_count)"
    }
   ]
  },
  {
   "title": "Node: $node",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 12, "x": 0, "y": 6 },
   "repeat": "node",
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "kubelet_running_pod_count{instance=~\"$node\"}"
    }
   ]
  },
  {
   "title": "Node: $node",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 12, "x": 12, "y": 6 },
   "repeat": "node",
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "kubelet_running_container_count{instance=~\"$node\"}"
    }
   ]
  },
  {
   "title": "Node Resource Usage",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 },
   "collapsed": true,
   "panels": [
    {
     "title": "Number of Node",
     "type": "singlestat",
     "gridPos": { "h": 3, "w": 4, "x": 0, "y": 35 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "count(node_uname_info{job=\"kubernetes-nodes-exporter\"})"
      }
     ]
    },
    {
     "title": "Total CPU",
     "type": "singlestat",
     "gridPos": { "h": 3, "w": 4, "x": 4, "y": 35 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "count(node_cpu{mode=\"user\",component=\"node-exporter\"})"
      }
     ]
    },
    {
     "title": "Used Memery",
     "type": "singlestat",
     "gridPos": { "h": 3, "w": 4, "x": 8, "y": 35 },
     "format": "bytes",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum(node_memory_MemTotal{job=\"kubernetes-nodes-exporter\"} - node_memory_MemFree - node_memory_Buffers - node_memory_Cached)"
      }
     ]
    },
    {
     "title": "Total Memery",
     "type": "singlestat",
     "gridPos": { "h": 3, "w": 4, "x": 12, "y": 35 },
     "format": "bytes",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum(node_memory_MemTotal{job=\"kubernetes-nodes-exporter\"})"
      }
     ]
    },
    {
     "title": "DIsk Usage(Local)",
     "type": "singlestat",
     "gridPos": { "h": 3, "w": 4, "x": 16, "y": 35 },
     "format": "bytes",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum(node_filesystem_size{job=\"kubernetes-nodes-exporter\",mountpoint=\"/\"}) - sum(node_filesystem_avail{job=\"kubernetes-nodes-exporter\",mountpoint=\"/\"})"
      }
     ]
    },
    {
     "title": "DIsk Total(Local)",
     "type": "singlestat",
     "gridPos": { "h": 3, "w": 4, "x": 20, "y": 35 },
     "format": "bytes",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum(node_filesystem_size{job=\"kubernetes-nodes-exporter\",mountpoint=\"/\"})"
      }
     ]
    },
    {
     "title": "Avg CPU Usage",
     "type": "singlestat",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 38 },
     "format": "percent",
     "valueName": "current",
     "targets": [
      {
       "expr": "avg(100 - (avg by (cpu) (rate(node_cpu{job=\"kubernetes-nodes-exporter\",mode=\"idle\"}[5m])) * 100))"
      }
     ]
    },
    {
     "title": "Avg Memory Usage",
     "type": "singlestat",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 38 },
     "format": "percent",
     "valueName": "avg",
     "targets": [
      {
       "expr": "sum(node_memory_MemTotal{job=\"kubernetes-nodes-exporter\"} - node_memory_MemFree - node_memory_Buffers - node_memory_Cached ) / sum(node_memory_MemTotal{job=\"kubernetes-nodes-exporter\"}) * 100"
      }
     ]
    },
    {
     "title": "Avg Disk Usage(Local)",
     "type": "singlestat",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 38 },
     "format": "percent",
     "valueName": "avg",
     "targets": [
      {
       "expr": "((sum(node_filesystem_size{job=\"kubernetes-nodes-exporter\",mountpoint=\"/\"}) - sum(node_filesystem_avail{job=\"kubernetes-nodes-exporter\",mountpoint=\"/\"})) / sum(node_filesystem_size{job=\"kubernetes-nodes-exporter\",mountpoint=\"/\"})) * 100"
      }
     ]
    },
    {
     "title": "CPU Usage",
     "type": "graph",
     "gridPos": { "h": 7, "w": 6, "x": 0, "y": 45 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "expr": "100 - (avg by (instance) (rate(node_cpu{job=\"kubernetes-nodes-exporter\",mode=\"idle\"}[5m])) * 100)",
       "legendFormat": "{{ instance }}"
      }
     ]
    },
    {
     "title": "Memory Usage",
     "type": "graph",
     "gridPos": { "h": 7, "w": 6, "x": 6, "y": 45 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "expr": "((node_memory_MemTotal{job=\"kubernetes-nodes-exporter\"} - node_memory_MemFree - node_memory_Buffers - node_memory_Cached) / node_memory_MemTotal{job=\"kubernetes-nodes-exporter\"}) * 100",
       "legendFormat": "{{ instance }}"
      }
     ]
    },
    {
     "title": "Disk Usage(Local)",
     "type": "graph",
     "gridPos": { "h": 7, "w": 6, "x": 12, "y": 45 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "expr": "((node_filesystem_size{job=\"kubernetes-nodes-exporter\",mountpoint=\"/\"} - node_filesystem_avail{job=\"kubernetes-nodes-exporter\",mountpoint=\"/\"}) / node_filesystem_size{job=\"kubernetes-nodes-exporter\",mountpoint=\"/\"}) * 100",
       "legendFormat": "{{ instance }}"
      }
     ]
    },
    {
     "title": "Network Usage(RX/TX)",
     "type": "graph",
     "gridPos": { "h": 7, "w": 6, "x": 18, "y": 45 },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "expr": "(sum by (instance) (rate(node_network_receive_bytes{job=\"kubernetes-nodes-exporter\",device=~\"eth0|eth1\"}[5m])))",
       "legendFormat": "Inbound: {{ instance }} "
      },
      {
       "expr": "(sum by (instance) (rate(node_network_transmit_bytes{job=\"kubernetes-nodes-exporter\",device=~\"eth0|eth1\"}[5m])))",
       "legendFormat": "Outbound: {{ instance }}"
      }
     ]
    }
   ]
  },
  {
   "title": "Cluster Resource Usage",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 },
   "collapsed": true,
   "panels": [
    {
     "title": "Cluster CPU usage",
     "type": "singlestat",
     "gridPos": { "h": 6, "w": 8, "x": 0, "y": 53 },
     "format": "percent",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum(rate(container_cpu_usage_seconds_total{id=\"/\"}[5m])) / sum(kube_node_status_capacity_cpu_cores) * 100"
      }
     ]
    },
    {
     "title": "Cluster Memory usage",
     "type": "singlestat",
     "gridPos": { "h": 6, "w": 8, "x": 8, "y": 53 },
     "format": "percent",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum(container_memory_working_set_bytes{id=\"/\"}) / sum(kube_node_status_capacity_memory_bytes) * 100"
      }
     ]
    },
    {
     "title": "Cluster Disk usage(Local)",
     "type": "singlestat",
     "gridPos": { "h": 6, "w": 8, "x": 16, "y": 53 },
     "format": "percent",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum(container_fs_usage_bytes{id=\"/\",device=\"/dev/mapper/docker_data\"}) / sum(container_fs_limit_bytes{id=\"/\",device=\"/dev/mapper/docker_data\"}) * 100"
      }
     ]
    },
    {
     "title": "Used",
     "type": "singlestat",
     "gridPos": { "h": 6, "w": 4, "x": 0, "y": 59 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum(rate(container_cpu_usage_seconds_total{id=\"/\"}[2m]))"
      }
     ]
    },
    {
     "title": "Total",
     "type": "singlestat",
     "gridPos": { "h": 6, "w": 4, "x": 4, "y": 59 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum(kube_node_status_capacity_cpu_cores)"
      }
     ]
    },
    {
     "title": "Used",
     "type": "singlestat",
     "gridPos": { "h": 6, "w": 4, "x": 8, "y": 59 },
     "format": "bytes",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum(container_memory_working_set_bytes{id=\"/\"})"
      }
     ]
    },
    {
     "title": "Total",
     "type": "singlestat",
     "gridPos": { "h": 6, "w": 4, "x": 12, "y": 59 },
     "format": "bytes",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum(kube_node_status_capacity_memory_bytes)"
      }
     ]
    },
    {
     "title": "Used",
     "type": "singlestat",
     "gridPos": { "h": 6, "w": 4, "x": 16, "y": 59 },
     "format": "bytes",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum(container_fs_usage_bytes{id=\"/\",device=\"/dev/mapper/docker_data\"})"
      }
     ]
    },
    {
     "title": "Total",
     "type": "singlestat",
     "gridPos": { "h": 6, "w": 4, "x": 20, "y": 59 },
     "format": "bytes",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum(container_fs_limit_bytes{id=\"/\",device=\"/dev/mapper/docker_data\"})"
      }
     ]
    },
    {
     "title": "Pod Count",
     "type": "graph",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 65 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "count by (namespace) (kube_pod_info)",
       "legendFormat": "{{ namespace }}"
      }
     ]
    },
    {
     "title": "Container Count",
     "type": "graph",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 65 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "count by (namespace) (kube_pod_container_info)",
       "legendFormat": "{{ namespace }}"
      }
     ]
    }
   ]
  }
 ]
}
{
 "title": "Kubernetes: Performance Overview",
 "description": "Used to view and monitor Kubernetes performance",
 "tags": [ "kubernetes" ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "1m",
 "panels": [
  {
   "title": "API Server Requests (Req/Sec)",
   "type": "graph",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum(rate(apiserver_request_count[2m]))",
     "legendFormat": "Requests"
    }
   ]
  },
  {
   "title": "API Server Latency",
   "type": "graph",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 5 },
   "yaxes": [
    { "format": "ns" }
   ],
   "targets": [
    {
     "expr": "avg(apiserver_request_latencies_sum / apiserver_request_latencies_count)",
     "legendFormat": "Latency"
    }
   ]
  },
  {
   "title": "Kubelet Pod Start Latency",
   "type": "graph",
   "description": "Latency in microseconds for a single pod to go from pending to running. Broken down by podname.",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "µs" }
   ],
   "targets": [
    {
     "expr": "rate(kubelet_pod_start_latency_microseconds_sum[5m]) / rate(kubelet_pod_start_latency_microseconds_count[5m])",
     "legendFormat": "kubelet - {{instance}}"
    }
   ]
  },
  {
   "title": "Running Pods Trands",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "kubelet_running_pod_count", "legendFormat": "{{instance}}" }
   ]
  },
  {
   "title": "Creating Rate of Pods",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(kubelet_running_pod_count[2m])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Running Containers Trands",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 31 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kubelet_running_container_count",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Creating Rate of Containers",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 38 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(kubelet_running_container_count[2m])",
     "legendFormat": "{{instance}}"
    }
   ]
  }
 ]
}
{
 "title": "Kubernetes: Resource Requests",
 "description": "Dashboard to show the resource requests vs allocatable in the cluster",
 "tags": [ "kubernetes" ],
 "time": { "from": "now-3h", "to": "now" },
 "panels": [
  {
   "title": "CPU Cores",
   "type": "graph",
   "description": "This represents the total [CPU resource requests](https://kubernetes.io/docs/concepts/configuration/manage-compute-resources-container/#meaning-of-cpu) in the cluster.\nFor comparison the total [allocatable CPU cores](https://github.com/kubernetes/community/blob/master/contributors/design-proposals/node-allocatable.md) is also shown.",
   "gridPos": { "h": 8, "w": 18, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short", "label": "CPU Cores" }
   ],
   "targets": [
    {
     "expr": "min(sum(kube_node_status_allocatable_cpu_cores) by (instance))",
     "legendFormat": "Allocatable CPU Cores"
    },
    {
     "expr": "max(sum(kube_pod_container_resource_requests_cpu_cores) by (instance))",
     "legendFormat": "Requested CPU Cores"
    }
   ]
  },
  {
   "title": "CPU Cores",
   "type": "singlestat",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 0 },
   "format": "percent",
   "valueName": "avg",
   "targets": [
    {
     "expr": "max(sum(kube_pod_container_resource_requests_cpu_cores) by (instance)) / min(sum(kube_node_status_allocatable_cpu_cores) by (instance)) * 100"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "graph",
   "description": "This represents the total [memory resource requests](https://kubernetes.io/docs/concepts/configuration/manage-compute-resources-container/#meaning-of-memory) in the cluster.\nFor comparison the total [allocatable memory](https://github.com/kubernetes/community/blob/master/contributors/design-proposals/node-allocatable.md) is also shown.",
   "gridPos": { "h": 8, "w": 18, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "bytes", "label": "Memory" }
   ],
   "targets": [
    {
     "expr": "min(sum(kube_node_status_allocatable_memory_bytes) by (instance))",
     "legendFormat": "Allocatable Memory"
    },
    {
     "expr": "max(sum(kube_pod_container_resource_requests_memory_bytes) by (instance))",
     "legendFormat": "Requested Memory"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "singlestat",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 8 },
   "format": "percent",
   "valueName": "avg",
   "targets": [
    {
     "expr": "max(sum(kube_pod_container_resource_requests_memory_bytes) by (instance)) / min(sum(kube_node_status_allocatable_memory_bytes) by (instance)) * 100"
    }
   ]
  },
  {
   "title": "Cluster Pod Utilization",
   "type": "graph",
   "gridPos": { "h": 8, "w": 18, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short", "label": "Pod Count" }
   ],
   "targets": [
    { "expr": "sum(kube_pod_info)", "legendFormat": "Current number of Pods" },
    {
     "expr": "sum(kube_node_status_capacity_pods)",
     "legendFormat": "Maximum capacity of pods"
    }
   ]
  },
  {
   "title": "Pod Utilization",
   "type": "singlestat",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 16 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "100 - (sum(kube_node_status_capacity_pods) - sum(kube_pod_info)) / sum(kube_node_status_capacity_pods) * 100"
    }
   ]
  }
 ]
}