apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
  creationTimestamp: 2020-02-06T09:27:33Z
  generation: 1
  labels:
    app.kubernetes.io/instance: prometheus-snmp-exporter
    app.kubernetes.io/managed-by: Tiller
    app.kubernetes.io/name: prometheus-snmp-exporter
    helm.sh/chart: prometheus-snmp-exporter-0.0.4
  name: prometheus-snmp-exporter
  namespace: zcp-system
  resourceVersion: "114717068"
  selfLink: /apis/extensions/v1beta1/namespaces/zcp-system/deployments/prometheus-snmp-exporter
  uid: 573ffe01-3b25-4ae3-a389-5c30686c3d8c
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app.kubernetes.io/instance: prometheus-snmp-exporter
      app.kubernetes.io/name: prometheus-snmp-exporter
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/instance: prometheus-snmp-exporter
        app.kubernetes.io/managed-by: Tiller
        app.kubernetes.io/name: prometheus-snmp-exporter
        helm.sh/chart: prometheus-snmp-exporter-0.0.4
    spec:
      containers:
      - image: prom/snmp-exporter:v0.14.0
        imagePullPolicy: IfNotPresent
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /health
            port: http
            scheme: HTTP
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        name: snmp-exporter
        ports:
        - containerPort: 9116
          name: http
          protocol: TCP
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /health
            port: http
            scheme: HTTP
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        resources: {}
        securityContext:
          readOnlyRootFilesystem: true
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      serviceAccount: prometheus-snmp-exporter
      serviceAccountName: prometheus-snmp-exporter
      terminationGracePeriodSeconds: 30
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: 2020-02-06T09:27:33Z
    lastUpdateTime: 2020-02-06T09:27:44Z
    message: ReplicaSet "prometheus-snmp-exporter-849b575f89" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  - lastTransitionTime: 2020-03-12T15:23:35Z
    lastUpdateTime: 2020-03-12T15:23:35Z
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  observedGeneration: 1
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1
