apiVersion: v1
data:
  prometheus-zdb.rules: |
    groups:
    - name: prometheus-zdb.rules
      rules:
      - alert: ZDB-MariaDB-PodHealthCheck-zdb-portal-db-mariadb
        annotations:
          description: 'MariaDB의 Pod 동작하지 않습니다. (서비스: {{ $labels.service }})'
          summary: Pod 동작 중단
        expr: absent(mysql_up{service="zdb-portal-db-mariadb"}) == 1
        for: 1m
        labels:
          channel: default
          namespace: zdb-system
          priority: P4
          product: zdb
          serviceName: zdb-portal-db
          severity: low
      - alert: ZDB-MariaDB-ContainerHealthCheck-zdb-portal-db-mariadb
        annotations:
          description: 'MariaDB 컨테이너의 동작이 중단되었습니다. (서비스: {{ $labels.pod }})'
          summary: MariaDB 컨테이너 동작 중단
        expr: kube_pod_container_status_ready{pod=~"zdb-portal-db-mariadb.*", container="mariadb"} == 0
        for: 1m
        labels:
          channel: default
          namespace: zdb-system
          priority: P4
          product: zdb
          serviceName: zdb-portal-db
          severity: low
      - alert: ZDB-MariaDB-DBHealthCheck-zdb-portal-db-mariadb
        annotations:
          description: 'MariaDB의 동작이 중단되었습니다. (서비스: {{ $labels.service }})'
          summary: MariaDB 동작 중단
        expr: mysql_up{service=~"zdb-portal-db-mariadb.*"} == 0
        for: 1m
        labels:
          channel: default
          namespace: zdb-system
          priority: P4
          product: zdb
          serviceName: zdb-portal-db
          severity: low
      - alert: ZDB-MariaDB-CPUUsage-zdb-portal-db-mariadb
        annotations:
          description: 'CPU 사용량이 임계치를 초과하였습니다. (서비스: {{ $labels.pod_name }}, 임계값: 80%,
            현재값: {{ $value }}%)'
          summary: CPU 사용량 임계치 초과
        expr: sum(rate(container_cpu_usage_seconds_total{pod_name=~"zdb-portal-db-mariadb.*", container_name="mariadb"}[1m])) / sum(kube_pod_container_resource_limits_cpu_cores{pod=~"zdb-portal-db-mariadb.*", container="mariadb"}) * 100 > 80
        for: 1m
        labels:
          channel: default
          namespace: zdb-system
          priority: P4
          product: zdb
          serviceName: zdb-portal-db
          severity: low
      - alert: ZDB-MariaDB-MemoryUsage-zdb-portal-db-mariadb
        annotations:
          description: '메모리 사용량이 임계치를 초과하였습니다. (서비스: {{ $labels.pod_name }}, 임계값: 95%,
            현재값: {{ $value }}%)'
          summary: 메모리 사용량 임계치 초과
        expr: sum(container_memory_working_set_bytes{pod_name=~"zdb-portal-db-mariadb.*", container_name="mariadb"}) / sum(kube_pod_container_resource_limits_memory_bytes{pod=~"zdb-portal-db-mariadb.*", container="mariadb"}) * 100 > 95
        for: 1m
        labels:
          channel: default
          namespace: zdb-system
          priority: P4
          product: zdb
          serviceName: zdb-portal-db
          severity: low
      - alert: ZDB-MariaDB-Connections-zdb-portal-db-mariadb
        annotations:
          description: 'MariaDB의 Connnections값이 임계치를 초과하였습니다. (서비스: {{ $labels.service
            }}, 임계값: 80%, 현재값: {{ $value }}%)'
          summary: Connections 임계치 초과
        expr: (mysql_global_status_threads_connected{service=~"zdb-portal-db-mariadb.*"} / mysql_global_variables_max_connections{service=~"zdb-portal-db-mariadb.*"} * 100) > 80
        for: 1m
        labels:
          channel: default
          namespace: zdb-system
          priority: P4
          product: zdb
          serviceName: zdb-portal-db
          severity: low
      - alert: ZDB-MariaDB-SlowQueries-zdb-portal-db-mariadb
        annotations:
          description: 'MariaDB의 Slow Query가 발생했습니다. (서비스: {{ $labels.service }})'
          summary: MariaDB Slow Queries
        expr: 'false'
        for: 1m
        labels:
          channel: default
          namespace: zdb-system
          priority: P4
          product: zdb
          serviceName: zdb-portal-db
          severity: low
kind: ConfigMap
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","data":{"prometheus-zdb.rules":"groups:\n"},"kind":"ConfigMap","metadata":{"annotations":{},"name":"prometheus-zdb-rules","namespace":"zcp-system"}}
  creationTimestamp: 2019-04-23T08:37:56Z
  name: prometheus-zdb-rules
  namespace: zcp-system
  resourceVersion: "120609101"
  selfLink: /api/v1/namespaces/zcp-system/configmaps/prometheus-zdb-rules
  uid: 17874ccf-65a3-11e9-98d4-1e7b3ccf7f43
