apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"extensions/v1beta1","kind":"Deployment","metadata":{"annotations":{"kubernetes.io/change-cause":"kubectl apply --namespace=zcp-system --filename=./ --record=true"},"labels":{"app":"zcp-alertmanager-store"},"name":"zcp-alertmanager-store","namespace":"zcp-system"},"spec":{"selector":{"matchLabels":{"app":"zcp-alertmanager-store"}},"template":{"metadata":{"labels":{"app":"zcp-alertmanager-store"}},"spec":{"affinity":{"nodeAffinity":{"requiredDuringSchedulingIgnoredDuringExecution":{"nodeSelectorTerms":[{"matchExpressions":[{"key":"beta.kubernetes.io/arch","operator":"In","values":["amd64"]},{"key":"role","operator":"In","values":["management"]}]}]}}},"containers":[{"image":"registry.au-syd.bluemix.net/cloudzcp/zcp-alertmanager-store:1.0.0","imagePullPolicy":"Always","name":"zcp-alertmanager-store","ports":[{"containerPort":5000,"protocol":"TCP"}],"resources":{"limits":{"cpu":"800m","memory":"1Gi"},"requests":{"cpu":"200m","memory":"512Mi"}},"volumeMounts":[{"mountPath":"/etc/localtime","name":"tz-config"}]}],"tolerations":[{"effect":"NoSchedule","key":"management","operator":"Equal","value":"true"}],"volumes":[{"hostPath":{"path":"/usr/share/zoneinfo/Asia/Seoul"},"name":"tz-config"}]}}}}
    kubernetes.io/change-cause: kubectl apply --namespace=zcp-system --filename=./
      --record=true
  creationTimestamp: 2019-02-26T07:56:39Z
  generation: 1
  labels:
    app: zcp-alertmanager-store
  name: zcp-alertmanager-store
  namespace: zcp-system
  resourceVersion: "122915567"
  selfLink: /apis/extensions/v1beta1/namespaces/zcp-system/deployments/zcp-alertmanager-store
  uid: 0c50ad85-399c-11e9-814c-ca0890826a6e
spec:
  progressDeadlineSeconds: 2147483647
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: zcp-alertmanager-store
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: zcp-alertmanager-store
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: beta.kubernetes.io/arch
                operator: In
                values:
                - amd64
              - key: role
                operator: In
                values:
                - management
      containers:
      - image: registry.au-syd.bluemix.net/cloudzcp/zcp-alertmanager-store:1.0.0
        imagePullPolicy: Always
        name: zcp-alertmanager-store
        ports:
        - containerPort: 5000
          protocol: TCP
        resources:
          limits:
            cpu: 800m
            memory: 1Gi
          requests:
            cpu: 200m
            memory: 512Mi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /etc/localtime
          name: tz-config
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      tolerations:
      - effect: NoSchedule
        key: management
        operator: Equal
        value: "true"
      volumes:
      - hostPath:
          path: /usr/share/zoneinfo/Asia/Seoul
          type: ""
        name: tz-config
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: 2019-02-26T07:56:39Z
    lastUpdateTime: 2019-02-26T07:56:39Z
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  observedGeneration: 1
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1
